package com.example.utils

import android.content.Context
import android.content.SharedPreferences
import androidx.compose.runtime.Composable
import androidx.compose.runtime.State
import androidx.compose.runtime.mutableStateOf

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    MYANMAR("my", "မြန်မာ", "🇲🇲"),
    ENGLISH("en", "English", "🇬🇧")
}

data class AppStrings(
    // App Bar & Navigation
    val appName: String,
    val back: String,
    val refresh: String,
    val cancel: String,
    val delete: String,
    val save: String,
    val add: String,
    val edit: String,
    val close: String,
    val search: String,
    val all: String,
    val none: String,

    // Login Screen
    val connectToRouter: String,
    val routerIp: String,
    val username: String,
    val password: String,
    val rememberPassword: String,
    val secureConnect: String,
    val connecting: String,

    // Dashboard
    val realTimeTraffic: String,
    val downloadRx: String,
    val uploadTx: String,
    val hardwareConditions: String,
    val cpuLoad: String,
    val uptime: String,
    val freeMemory: String,
    val routerOs: String,
    val usageMetrics: String,
    val resetStats: String,
    val resetStatsTitle: String,
    val resetStatsMsg: String,
    val resetAllToZero: String,
    val dateToday: String,
    val dateYesterday: String,
    val date7Days: String,
    val date30Days: String,
    val dateAll: String,
    val activeSessionsStat: String,
    val totalDataUsage: String,
    val trackedClients: String,
    val activatedVoucherSales: String,
    val hotspotControls: String,
    val activeSessionsTitle: String,
    val activeSessionsSubtitle: String,
    val vouchersAccountsTitle: String,
    val vouchersAccountsSubtitle: String,
    val userProfilesTitle: String,
    val userProfilesSubtitle: String,

    // Update Dialog
    val updateAvailable: String,
    val appVersionInfo: String,
    val currentVersion: String,
    val latestVersion: String,
    val releaseNotes: String,
    val downloadingUpdate: String,
    val later: String,
    val downloadAndInstall: String,
    val updateNow: String,
    val checkUpdate: String,

    // Profiles Screen
    val profilesHeader: String,
    val cleanUpUnusedProfiles: String,
    val syncRouterProfiles: String,
    val addProfileTitle: String,
    val editProfileTitle: String,
    val noProfilesFound: String,
    val cleanupConfirmTitle: String,
    val cleanupConfirmMsg: String,
    val cleanUpAction: String,
    val profileName: String,
    val rateLimit: String,
    val sharedUsers: String,
    val validity: String,
    val originalPrice: String,
    val sellingPrice: String,
    val dataLimitMb: String,
    val durationMin: String,
    val deleteProfileTitle: String,
    val deleteProfileConfirmMsg: String,
    val vouchersCountSuffix: String,

    // Vouchers Screen
    val vouchersHeader: String,
    val searchVouchersHint: String,
    val filterAll: String,
    val filterUsed: String,
    val filterUnprinted: String,
    val filterPrinted: String,
    val printerSetupBtn: String,
    val usedVouchersBanner: String,
    val renewAll: String,
    val deleteAll: String,
    val printAction: String,
    val deleteAction: String,
    val deselectAll: String,
    val printOnlyUnprinted: String,
    val selectAll: String,
    val generateVouchers: String,
    val quantity: String,
    val prefixOptional: String,
    val codeLength: String,
    val characterType: String,
    val userMode: String,
    val userModeSame: String,
    val userModeSeparate: String,
    val charNumbers: String,
    val charUppercase: String,
    val charLowercase: String,
    val charMixed: String,
    val deleteSelectedConfirmTitle: String,
    val deleteSelectedConfirmMsg: String,
    val deleteAllUsedConfirmTitle: String,
    val deleteAllUsedConfirmMsg: String,
    val thermalPrinterSetupTitle: String,
    val pairedDevices: String,
    val connectPrinter: String,
    val printerConnected: String,
    val printerDisconnect: String,
    val testPrint: String,
    val openBtSettings: String,
    val printLayout: String,
    val printVouchersTitle: String,
    val copiedToClipboard: String,
    val statusUsed: String,
    val statusUnused: String,
    val statusPrinted: String,
    val statusUnprinted: String,
    val renewAction: String,

    // Active Sessions Screen
    val searchSessionsHint: String,
    val kickClient: String,
    val banMac: String,
    val bytesInOut: String,
    val kickConfirmTitle: String,
    val kickConfirmMsg: String,
    val banConfirmTitle: String,
    val banConfirmMsg: String,
    val kickAction: String,
    val banAction: String,
    val noActiveSessions: String,

    // Language Toggle
    val switchLanguage: String,

    // Settings, Printer & Password
    val settings: String,
    val printerFunctions: String,
    val changePasswordTitle: String,
    val currentPassword: String,
    val newPassword: String,
    val confirmNewPassword: String,
    val passwordMismatch: String,
    val passwordChangedSuccess: String,
    val logoutRouter: String,
    val activePrinter: String,
    val paperWidthTitle: String,
    val autoCutOption: String,

    // Network Topology & Whitelisting
    val networkTopology: String,
    val allowlistAp: String,
    val allowlistApConfirm: String,
    val whitelistedClients: String,
    val bannedClients: String,
    val activeClientsTab: String,
    val whitelistAction: String,
    val undoAction: String,
    val addDevice: String,
    val gateway: String,
    val accessPoint: String,
    val switchRouterAdvanceMode: String,
    val advanceModeSuccess: String,
    val deviceWhitelistedSuccess: String,
    val deviceRemovedFromWhitelist: String,
    val unbanSuccess: String
)

val MyanmarStrings = AppStrings(
    // App Bar & Navigation
    appName = "ဟော့စပေါ့ မန်နေဂျာ",
    back = "နောက်သို့",
    refresh = "ပြန်ဖွင့်မည်",
    cancel = "မလုပ်တော့ပါ",
    delete = "ဖျက်မည်",
    save = "သိမ်းဆည်းမည်",
    add = "အသစ်ထည့်မည်",
    edit = "ပြင်ဆင်မည်",
    close = "ပိတ်မည်",
    search = "ရှာဖွေပါ",
    all = "အားလုံး",
    none = "မရှိပါ",

    // Login Screen
    connectToRouter = "MikroTik RouterOS သို့ ချိတ်ဆက်ပါ",
    routerIp = "Router IP",
    username = "အသုံးပြုသူအမည် (Username)",
    password = "စကားဝှက် (Password)",
    rememberPassword = "စကားဝှက် မှတ်ထားမည်",
    secureConnect = "လုံခြုံစွာ ချိတ်ဆက်မည်",
    connecting = "ချိတ်ဆက်နေသည်...",

    // Dashboard
    realTimeTraffic = "လက်ရှိ အင်တာနက် အသွားအလာနှုန်း",
    downloadRx = "ဒေါင်းလုဒ် (Rx)",
    uploadTx = "အပ်ပလုဒ် (Tx)",
    hardwareConditions = "Router ဟာ့ဒ်ဝဲ အခြေအနေ",
    cpuLoad = "CPU သုံးစွဲမှု",
    uptime = "စတင်ဖွင့်ချိန်",
    freeMemory = "ကျန်ရှိသော RAM",
    routerOs = "RouterOS",
    usageMetrics = "သုံးစွဲမှု အချက်အလက်",
    resetStats = "ပြန်စမည်",
    resetStatsTitle = "စာရင်း အားလုံး ပြန်စမလား?",
    resetStatsMsg = "Router ၏ အင်တာဖေ့စ် ဒေတာ စာရင်းများ၊ ဟော့စပေါ့ အသုံးပြုသူ စာရင်းများနှင့် ဒေတာ မှတ်တမ်းများကို သုညသို့ ပြန်စပါမည်။",
    resetAllToZero = "သုညသို့ အားလုံး ပြန်စမည်",
    dateToday = "ဒီနေ့",
    dateYesterday = "မနေ့က",
    date7Days = "၇ ရက်",
    date30Days = "၃၀ ရက်",
    dateAll = "အားလုံး",
    activeSessionsStat = "လက်ရှိသုံးစွဲသူ",
    totalDataUsage = "သုံးစွဲဒေတာ",
    trackedClients = "စုစုပေါင်းစက်",
    activatedVoucherSales = "ရောင်းရငွေ",
    hotspotControls = "ဟော့စပေါ့ ထိန်းချုပ်မှုများ",
    activeSessionsTitle = "လက်ရှိ အသုံးပြုနေသူများ",
    activeSessionsSubtitle = "ဦး အွန်လိုင်း",
    vouchersAccountsTitle = "ဘောင်ချာနှင့် အကောင့်များ",
    vouchersAccountsSubtitle = "Mikhmon ဘောင်ချာ • ပရင့်ထုတ်ခြင်း",
    userProfilesTitle = "အသုံးပြုသူ ပရိုဖိုင်များ",
    userProfilesSubtitle = "အမြန်နှုန်း • သက်တမ်း • ဈေးနှုန်း",

    // Update Dialog
    updateAvailable = "ဗားရှင်းအသစ် ရရှိနေပါပြီ!",
    appVersionInfo = "ဗားရှင်း အချက်အလက်",
    currentVersion = "လက်ရှိ",
    latestVersion = "ဗားရှင်းအသစ်",
    releaseNotes = "အသစ်ပြောင်းလဲချက်များ",
    downloadingUpdate = "အပ်ဒိတ် ဒေါင်းလုဒ်ဆွဲနေသည်",
    later = "နောက်မှ",
    downloadAndInstall = "ဒေါင်းလုဒ်ဆွဲပြီး ထည့်မည်",
    updateNow = "အခုပဲ အပ်ဒိတ်လုပ်မည်",
    checkUpdate = "အပ်ဒိတ် စစ်ဆေးရန်",

    // Profiles Screen
    profilesHeader = "အသုံးပြုသူ ပရိုဖိုင်များ",
    cleanUpUnusedProfiles = "မသုံးသော ပရိုဖိုင် ရှင်းမည်",
    syncRouterProfiles = "Router Sync",
    addProfileTitle = "ပရိုဖိုင် အသစ်ထည့်မည်",
    editProfileTitle = "ပရိုဖိုင် ပြင်ဆင်မည်",
    noProfilesFound = "ပရိုဖိုင် မရှိသေးပါ။ Sync သို့မဟုတ် + ကို နှိပ်ပါ။",
    cleanupConfirmTitle = "မသုံးသော ပရိုဖိုင်များ ရှင်းလင်းမည်",
    cleanupConfirmMsg = "ဘောင်ချာ မရှိသော ပရိုဖိုင်များကို RouterOS နှင့် ဒေတာဘေ့စ်မှ ဖျက်ပစ်ရန် သေချာပါသလား?",
    cleanUpAction = "ရှင်းလင်းမည်",
    profileName = "ပရိုဖိုင် အမည်",
    rateLimit = "အမြန်နှုန်း",
    sharedUsers = "မျှဝေသုံးသူ",
    validity = "သက်တမ်း",
    originalPrice = "မူရင်းဈေး (Ks)",
    sellingPrice = "ရောင်းဈေး (Ks)",
    dataLimitMb = "ဒေတာ",
    durationMin = "ကြာချိန် (မိနစ်)",
    deleteProfileTitle = "ပရိုဖိုင် ဖျက်မည်",
    deleteProfileConfirmMsg = "ဤပရိုဖိုင်ကို RouterOS နှင့် ဒေတာဘေ့စ်မှ ဖျက်ရန် သေချာပါသလား?",
    vouchersCountSuffix = "ခု",

    // Vouchers Screen
    vouchersHeader = "ဘောင်ချာများ",
    searchVouchersHint = "ကုဒ် သို့မဟုတ် ပရိုဖိုင်ဖြင့် ရှာပါ...",
    filterAll = "အားလုံး",
    filterUsed = "သုံးပြီး",
    filterUnprinted = "မထုတ်သေး",
    filterPrinted = "ထုတ်ပြီး",
    printerSetupBtn = "ပရင်တာ စနစ်",
    usedVouchersBanner = "သုံးပြီးသား ဘောင်ချာများ",
    renewAll = "အားလုံး သက်တမ်းတိုး",
    deleteAll = "အားလုံး ဖျက်မည်",
    printAction = "ပရင့်ထုတ်မည်",
    deleteAction = "ဖျက်မည်",
    deselectAll = "ရွေးချယ်မှု ပယ်ဖျက်",
    printOnlyUnprinted = "မထုတ်သေး ပရင့်",
    selectAll = "အားလုံး ရွေးမည်",
    generateVouchers = "ဘောင်ချာ ထုတ်ယူခြင်း",
    quantity = "အရေအတွက်",
    prefixOptional = "Prefix (ရွေးချယ်နိုင်)",
    codeLength = "ကုဒ် အလျား",
    characterType = "စာလုံး ပုံစံ",
    userMode = "အကောင့် ပုံစံ",
    userModeSame = "ဘောင်ချာ (User = Pass)",
    userModeSeparate = "အကောင့် (User + Pass)",
    charNumbers = "ဂဏန်း (12345)",
    charUppercase = "စာလုံးကြီး (ABCDE)",
    charLowercase = "စာလုံးသေး (abcde)",
    charMixed = "ရောနှော (A-Z, 0-9)",
    deleteSelectedConfirmTitle = "ရွေးထားသော ဘောင်ချာများ ဖျက်မလား?",
    deleteSelectedConfirmMsg = "ရွေးချယ်ထားသော ဘောင်ချာများကို RouterOS နှင့် ဖုန်းမှ အပြီးတိုင် ဖျက်ပါမည်။",
    deleteAllUsedConfirmTitle = "သုံးပြီးသား ဘောင်ချာများ ဖျက်မလား?",
    deleteAllUsedConfirmMsg = "သုံးပြီးသား ဘောင်ချာအားလုံးကို RouterOS နှင့် ဖုန်းမှ အပြီးတိုင် ဖျက်ပါမည်။",
    thermalPrinterSetupTitle = "ပရင်တာ ချိတ်ဆက်ခြင်း",
    pairedDevices = "ချိတ်ဆက်ထားသော စက်များ",
    connectPrinter = "ချိတ်ဆက်မည်",
    printerConnected = "ချိတ်ဆက်ပြီး",
    printerDisconnect = "ဖြုတ်မည်",
    testPrint = "စမ်းသပ်ပရင့်",
    openBtSettings = "ဘလူးတုသ် ဆက်တင်",
    printLayout = "ပရင့်ပုံစံ",
    printVouchersTitle = "ဘောင်ချာများ ပရင့်ထုတ်မည်",
    copiedToClipboard = "ဘောင်ချာကုဒ် ကူးယူပြီးပါပြီ",
    statusUsed = "သုံးပြီး",
    statusUnused = "မသုံးသေး",
    statusPrinted = "ထုတ်ပြီး",
    statusUnprinted = "မထုတ်သေး",
    renewAction = "သက်တမ်းတိုး",

    // Active Sessions Screen
    searchSessionsHint = "အသုံးပြုသူ၊ IP၊ MAC ဖြင့် ရှာပါ...",
    kickClient = "ဖြုတ်ချမည်",
    banMac = "MAC ပိတ်မည်",
    bytesInOut = "ဒေါင်းလုဒ် / အပ်ပလုဒ်",
    kickConfirmTitle = "အသုံးပြုသူအား ဖြုတ်ချမလား?",
    kickConfirmMsg = "ဤအသုံးပြုသူအား ဖြုတ်ချရန် သေချာပါသလား? အကောင့်မှန်ကန်ပါက ပြန်လည်ဝင်ရောက်နိုင်ပါသည်။",
    banConfirmTitle = "MAC လိပ်စာ ပိတ်ပင်မလား?",
    banConfirmMsg = "ဤစက်၏ MAC လိပ်စာကို ပိတ်ပင်ရန် သေချာပါသလား? ဤစက်သည် အင်တာနက် အသုံးပြုခွင့် ပိတ်ပင်ခံရပါမည်။",
    kickAction = "ဖြုတ်ချမည်",
    banAction = "ပိတ်ပင်မည်",
    noActiveSessions = "လက်ရှိ အသုံးပြုနေသူ မရှိပါ။",

    // Language Toggle
    switchLanguage = "မြန်မာ",

    // Settings, Printer & Password
    settings = "ဆက်တင်များ",
    printerFunctions = "ပရင်တာ စမ်းသပ်ခြင်းနှင့် လုပ်ဆောင်ချက်များ",
    changePasswordTitle = "Router လော့ဂ်အင် စကားဝှက် ပြောင်းလဲခြင်း",
    currentPassword = "လက်ရှိ စကားဝှက်",
    newPassword = "စကားဝှက် အသစ်",
    confirmNewPassword = "စကားဝှက် အသစ် အတည်ပြုပါ",
    passwordMismatch = "စကားဝှက် မတူညီပါ",
    passwordChangedSuccess = "စကားဝှက် အောင်မြင်စွာ ပြောင်းလဲပြီးပါပြီ!",
    logoutRouter = "ချိတ်ဆက်မှု ဖြုတ်မည်",
    activePrinter = "အသုံးပြုနေသော ပရင်တာ",
    paperWidthTitle = "စက္ကူအရွယ်အစား ရွေးချယ်မှု",
    autoCutOption = "ဘောင်ချာတစ်ခုချင်းစီ အလိုအလျောက် ဖြတ်မည်",

    // Network Topology & Whitelisting
    networkTopology = "Network Topology",
    allowlistAp = "AP အား Allowlist လုပ်မည်",
    allowlistApConfirm = "ဤ Access Point အား Captive Portal စစ်ဆေးမှုမလိုဘဲ အင်တာနက် အသုံးပြုခွင့် (Allowlist/Bypass) ပေးရန် သေချာပါသလား?",
    whitelistedClients = "ခွင့်ပြုထားသော စက်များ",
    bannedClients = "ပိတ်ပင်ထားသော စက်များ",
    activeClientsTab = "လက်ရှိ သုံးစွဲသူများ",
    whitelistAction = "Whitelist ပေးမည်",
    undoAction = "ပြန်လည်ဖယ်ရှားမည်",
    addDevice = "Add Device",
    gateway = "Gateway",
    accessPoint = "Access Point",
    switchRouterAdvanceMode = "Advance Mode သို့ ပြောင်းမည်",
    advanceModeSuccess = "Router အား Advance Mode သို့ အောင်မြင်စွာ ပြောင်းလဲပြီးပါပြီ!",
    deviceWhitelistedSuccess = "စက်အား အောင်မြင်စွာ Whitelist ပေးပြီးပါပြီ!",
    deviceRemovedFromWhitelist = "Whitelist မှ အောင်မြင်စွာ ပြန်လည် ဖယ်ရှားပြီးပါပြီ!",
    unbanSuccess = "ပိတ်ပင်ထားခြင်းမှ အောင်မြင်စွာ ပြန်လည် ဖွင့်ပေးပြီးပါပြီ!"
)

val EnglishStrings = AppStrings(
    // App Bar & Navigation
    appName = "Hotspot Manager",
    back = "Back",
    refresh = "Refresh",
    cancel = "Cancel",
    delete = "Delete",
    save = "Save",
    add = "Add",
    edit = "Edit",
    close = "Close",
    search = "Search",
    all = "All",
    none = "None",

    // Login Screen
    connectToRouter = "Connect to MikroTik RouterOS",
    routerIp = "Router IP",
    username = "Username",
    password = "Password",
    rememberPassword = "Remember Password for Easy Login",
    secureConnect = "Secure Connect",
    connecting = "Connecting...",

    // Dashboard
    realTimeTraffic = "Real-Time Traffic Rate",
    downloadRx = "Download (Rx)",
    uploadTx = "Upload (Tx)",
    hardwareConditions = "Hardware Conditions",
    cpuLoad = "CPU Load",
    uptime = "Uptime",
    freeMemory = "Free Memory",
    routerOs = "RouterOS",
    usageMetrics = "Usage Metrics",
    resetStats = "Reset Stats",
    resetStatsTitle = "Reset All Statistics?",
    resetStatsMsg = "This will reset all router interface traffic counters, reset all hotspot user data counters, and clear local usage session tracking history to zero.",
    resetAllToZero = "Reset All to Zero",
    dateToday = "Today",
    dateYesterday = "Yesterday",
    date7Days = "Last 7 Days",
    date30Days = "Last 30 Days",
    dateAll = "All",
    activeSessionsStat = "Active Sessions",
    totalDataUsage = "Total Data Usage",
    trackedClients = "Tracked Clients",
    activatedVoucherSales = "Activated Voucher Sales",
    hotspotControls = "Hotspot Controls",
    activeSessionsTitle = "Active Sessions",
    activeSessionsSubtitle = "clients online • Kick / Ban MAC",
    vouchersAccountsTitle = "Vouchers & Accounts",
    vouchersAccountsSubtitle = "Generate Mikhmon codes • 58/80mm & A4 Print",
    userProfilesTitle = "User Profiles",
    userProfilesSubtitle = "Bandwidth limits (Rate-limit) • Validity • Prices",

    // Update Dialog
    updateAvailable = "Update Available!",
    appVersionInfo = "App Version Info",
    currentVersion = "Current",
    latestVersion = "Latest",
    releaseNotes = "Release Notes",
    downloadingUpdate = "Downloading update",
    later = "Later",
    downloadAndInstall = "Download & Install",
    updateNow = "Update Now",
    checkUpdate = "Check for Update",

    // Profiles Screen
    profilesHeader = "User Profiles",
    cleanUpUnusedProfiles = "Clean Up Unused Profiles",
    syncRouterProfiles = "Sync Router Profiles",
    addProfileTitle = "Add Profile",
    editProfileTitle = "Edit Profile",
    noProfilesFound = "No profiles yet. Click Sync or + to add one.",
    cleanupConfirmTitle = "Clean Up Unused Profiles",
    cleanupConfirmMsg = "Are you sure you want to remove zero voucher profile(s) from RouterOS and database?",
    cleanUpAction = "Clean Up",
    profileName = "Profile Name",
    rateLimit = "Speed",
    sharedUsers = "Shared Users",
    validity = "Validity",
    originalPrice = "Price (Ks)",
    sellingPrice = "Selling Price (Ks)",
    dataLimitMb = "Data Quota",
    durationMin = "Duration",
    deleteProfileTitle = "Delete Profile",
    deleteProfileConfirmMsg = "Are you sure you want to delete this profile from RouterOS?",
    vouchersCountSuffix = "vouchers",

    // Vouchers Screen
    vouchersHeader = "Vouchers",
    searchVouchersHint = "Search vouchers by code or profile...",
    filterAll = "All",
    filterUsed = "Used",
    filterUnprinted = "Unprinted",
    filterPrinted = "Printed",
    printerSetupBtn = "Printer Connect & Test Print",
    usedVouchersBanner = "Used Vouchers",
    renewAll = "Renew All",
    deleteAll = "Delete All",
    printAction = "Print",
    deleteAction = "Delete",
    deselectAll = "Deselect All",
    printOnlyUnprinted = "Print Only Unprinted",
    selectAll = "Select All",
    generateVouchers = "Generate Vouchers",
    quantity = "Quantity",
    prefixOptional = "Prefix (Optional)",
    codeLength = "Code Length",
    characterType = "Characters",
    userMode = "User Mode",
    userModeSame = "Voucher (User = Pass)",
    userModeSeparate = "Account (User + Pass)",
    charNumbers = "Numbers only (12345)",
    charUppercase = "Uppercase only (ABCDE)",
    charLowercase = "Lowercase only (abcde)",
    charMixed = "Random Mixed (aB3k9)",
    deleteSelectedConfirmTitle = "Delete Selected Vouchers?",
    deleteSelectedConfirmMsg = "This will permanently delete selected vouchers from RouterOS and your device.",
    deleteAllUsedConfirmTitle = "Delete All Used Vouchers?",
    deleteAllUsedConfirmMsg = "This will permanently delete all used vouchers from RouterOS and your device.",
    thermalPrinterSetupTitle = "Thermal Printer Setup",
    pairedDevices = "Paired Bluetooth Devices",
    connectPrinter = "Connect",
    printerConnected = "Connected",
    printerDisconnect = "Disconnect",
    testPrint = "Test Print",
    openBtSettings = "Open Bluetooth Settings",
    printLayout = "Print Layout",
    printVouchersTitle = "Print Vouchers",
    copiedToClipboard = "Copied code to clipboard",
    statusUsed = "Used",
    statusUnused = "Unused",
    statusPrinted = "Printed",
    statusUnprinted = "Unprinted",
    renewAction = "Renew",

    // Active Sessions Screen
    searchSessionsHint = "Search by user, IP, or MAC...",
    kickClient = "Kick",
    banMac = "Ban MAC",
    bytesInOut = "Bytes In / Out",
    kickConfirmTitle = "Kick User Session?",
    kickConfirmMsg = "Are you sure you want to disconnect this user? They can log back in with valid credentials.",
    banConfirmTitle = "Ban MAC Address?",
    banConfirmMsg = "Are you sure you want to ban this MAC address? This device will be blocked from accessing the network.",
    kickAction = "Kick",
    banAction = "Ban",
    noActiveSessions = "No active sessions found.",

    // Language Toggle
    switchLanguage = "English",

    // Settings, Printer & Password
    settings = "Settings",
    printerFunctions = "Thermal Printer & Test Tools",
    changePasswordTitle = "Change Router Login Password",
    currentPassword = "Current Password",
    newPassword = "New Password",
    confirmNewPassword = "Confirm New Password",
    passwordMismatch = "Passwords do not match",
    passwordChangedSuccess = "Password updated successfully!",
    logoutRouter = "Disconnect / Logout",
    activePrinter = "Active Printer",
    paperWidthTitle = "Thermal Paper Width",
    autoCutOption = "Auto-Cut Each Voucher",

    // Network Topology & Whitelisting
    networkTopology = "Network Topology",
    allowlistAp = "Allowlist AP",
    allowlistApConfirm = "Are you sure you want to allowlist (bypass) this Access Point so it can access the network without voucher authentication?",
    whitelistedClients = "Whitelisted Clients",
    bannedClients = "Banned Clients",
    activeClientsTab = "Active Clients",
    whitelistAction = "Whitelist",
    undoAction = "Undo / Remove",
    addDevice = "Add Device",
    gateway = "Gateway",
    accessPoint = "Access Point",
    switchRouterAdvanceMode = "Switch to Advance Mode",
    advanceModeSuccess = "Router successfully switched to Advance Mode!",
    deviceWhitelistedSuccess = "Device successfully added to Whitelist!",
    deviceRemovedFromWhitelist = "Device removed from Whitelist!",
    unbanSuccess = "Device successfully unbanned!"
)

object LanguageManager {
    private const val PREFS_NAME = "app_language_prefs"
    private const val KEY_LANG = "selected_language"

    private val _currentLanguage = mutableStateOf(AppLanguage.MYANMAR)
    val currentLanguage: State<AppLanguage> = _currentLanguage

    val strings: AppStrings
        get() = if (_currentLanguage.value == AppLanguage.MYANMAR) MyanmarStrings else EnglishStrings

    fun init(context: Context) {
        val prefs: SharedPreferences = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val savedLang = prefs.getString(KEY_LANG, AppLanguage.MYANMAR.code)
        _currentLanguage.value = if (savedLang == AppLanguage.ENGLISH.code) AppLanguage.ENGLISH else AppLanguage.MYANMAR
    }

    fun setLanguage(context: Context, language: AppLanguage) {
        _currentLanguage.value = language
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_LANG, language.code).apply()
    }

    fun toggleLanguage(context: Context) {
        val next = if (_currentLanguage.value == AppLanguage.MYANMAR) AppLanguage.ENGLISH else AppLanguage.MYANMAR
        setLanguage(context, next)
    }
}
